// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuftzVP8RUnONrU_0d2A4q57ilj4f7MCs',
    appId: '1:862357758999:android:f4cbb83d7da48ba6332852',
    messagingSenderId: '862357758999',
    projectId: 'eatbits-b0f5e',
    storageBucket: 'eatbits-b0f5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvqFE84z-G8oOf0ukRyoMEJlStp07unaM',
    appId: '1:862357758999:ios:625219f709980639332852',
    messagingSenderId: '862357758999',
    projectId: 'eatbits-b0f5e',
    storageBucket: 'eatbits-b0f5e.appspot.com',
    iosClientId: '862357758999-nol8hg99lota3f5bnlcarm4bioe7jsm5.apps.googleusercontent.com',
    iosBundleId: 'com.eatbits.app',
  );
}
